apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digital-library
  template:
    metadata:
      labels:
        app: digital-library
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: media
              mountPath: /usr/share/nginx/html/assets

      # containers:
      #   - name: web
      #     image: digital-library-secure:v13
      #     ports:
      #       - containerPort: 80
      #     volumeMounts:
      #       - name: media
      #         mountPath: /usr/share/nginx/html/assets

      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: digital-library-media
       
