apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-library
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: digital-library
  template:
    metadata:
      labels:
        app: digital-library
    spec:
      containers:
        - name: digital-library
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80

          volumeMounts:
            - name: media
              mountPath: /usr/share/nginx/html/assets

      volumes:
        - name: media
          hostPath:
            path: /run/desktop/mnt/host/c/Digital-library-data
            type: Directory
