apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digital-library-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: digital-library.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: digital-library-service
                port:
                  number: 80
