apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digital-library-media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard   # 👈 VERY IMPORTANT
  resources:
    requests:
      storage: 10Gi
