apiVersion: v1
kind: Service
metadata:
  name: digital-library-service
  labels:
    app: digital-library
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: digital-library
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      protocol: TCP
      name: http