server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # MAIN APP
    location / {
        try_files $uri $uri/ /index.html;
    }

    # SERVE ASSETS (PDFs, videos)
    # location /assets/ {
    #     autoindex on;
    #     autoindex_exact_size off;
    #     autoindex_localtime on;
    #     charset utf-8;
    # }

    location /assets/ {
        alias /usr/share/nginx/html/assets/;
        autoindex on;
        types {
            application/pdf pdf;
            video/mp4 mp4;
            audio/mpeg mp3;
        }
}


    # SERVE THUMBNAILS (JPGs)
    location /content/ {
        autoindex off;
        expires 30d;
        add_header Cache-Control "public";
    }
}
