apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: digital-library-staging
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/YOUR_GITHUB/digital-library-platform
    path: helm/digital-library
    helm:
      valueFiles:
      - values-staging.yaml
  syncPolicy:
    automated: {}
