name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Frontend
        run: docker build -t frontend ./frontend

      - name: Build Backend
        run: docker build -t backend ./backend
