name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Build backend Docker image
      #   run: docker build -t digital-library-backend ./backend

      - name: Build frontend Docker image
        run: docker build -t digital-library-frontend ./frontend
