name: Security
on: [push]

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
    - name: Check Docker
      run: docker version
  
    - name: ZAP Baseline Scan
      run: |
        docker run --rm \
          -t owasp/zap2docker-stable \
          zap-baseline.py \
          -t http://host.docker.internal:8080 \
          -r zap-report.html

